//
// File generated by rootcint at Tue Sep 19 20:12:43 2017

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME mb_sorter_dict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "mb_sorter_dict.h"

#include "TCollectionProxyInfo.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void MBSorter_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_MBSorter(void *p = 0);
   static void *newArray_MBSorter(Long_t size, void *p);
   static void delete_MBSorter(void *p);
   static void deleteArray_MBSorter(void *p);
   static void destruct_MBSorter(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::MBSorter*)
   {
      ::MBSorter *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::MBSorter >(0);
      static ::ROOT::TGenericClassInfo 
         instance("MBSorter", ::MBSorter::Class_Version(), "./MBSorter.hh", 19,
                  typeid(::MBSorter), ::ROOT::DefineBehavior(ptr, ptr),
                  &::MBSorter::Dictionary, isa_proxy, 4,
                  sizeof(::MBSorter) );
      instance.SetNew(&new_MBSorter);
      instance.SetNewArray(&newArray_MBSorter);
      instance.SetDelete(&delete_MBSorter);
      instance.SetDeleteArray(&deleteArray_MBSorter);
      instance.SetDestructor(&destruct_MBSorter);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::MBSorter*)
   {
      return GenerateInitInstanceLocal((::MBSorter*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::MBSorter*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

//______________________________________________________________________________
atomic_TClass_ptr MBSorter::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *MBSorter::Class_Name()
{
   return "MBSorter";
}

//______________________________________________________________________________
const char *MBSorter::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::MBSorter*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int MBSorter::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::MBSorter*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void MBSorter::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::MBSorter*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *MBSorter::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::MBSorter*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void MBSorter::Streamer(TBuffer &R__b)
{
   // Stream an object of class MBSorter.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(MBSorter::Class(),this);
   } else {
      R__b.WriteClassBuffer(MBSorter::Class(),this);
   }
}

//______________________________________________________________________________
void MBSorter::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class MBSorter.
      TClass *R__cl = ::MBSorter::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fQObject", &fQObject);
      R__insp.InspectMember(fQObject, "fQObject.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*main_frame", &main_frame);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*left_frame", &left_frame);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*centre_frame", &centre_frame);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*right_frame", &right_frame);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*comp_frame_0", &comp_frame_0);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*comp_frame_1", &comp_frame_1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*comp_frame_2", &comp_frame_2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*comp_frame_3", &comp_frame_3);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*dop_frame_0", &dop_frame_0);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*dop_frame_1", &dop_frame_1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*dop_frame_2", &dop_frame_2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*sub_frame_0", &sub_frame_0);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*sub_frame_1", &sub_frame_1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*sub_frame_2", &sub_frame_2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*sub_frame_3", &sub_frame_3);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*sub_frame_4", &sub_frame_4);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*sub_frame_5", &sub_frame_5);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*sub_frame_6", &sub_frame_6);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*sub_frame_7", &sub_frame_7);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*sub_frame_8", &sub_frame_8);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*sub_frame_9", &sub_frame_9);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*sub_frame_10", &sub_frame_10);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*sub_frame_11", &sub_frame_11);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*sub_frame_12", &sub_frame_12);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fHorizontal_0", &fHorizontal_0);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fHorizontal_1", &fHorizontal_1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fHorizontal_2", &fHorizontal_2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fHorizontal_3", &fHorizontal_3);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fVertical_0", &fVertical_0);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fVertical_1", &fVertical_1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*lab_run_files", &lab_run_files);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*lab_daq_dir", &lab_daq_dir);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*lab_med_pre", &lab_med_pre);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*lab_local_dir", &lab_local_dir);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*lab_settings", &lab_settings);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*lab_last_entry", &lab_last_entry);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*lab_outfile", &lab_outfile);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*lab_outsuffix", &lab_outsuffix);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*lab_calfile", &lab_calfile);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*lab_dop_zb", &lab_dop_zb);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*lab_dop_zt", &lab_dop_zt);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*lab_dop_ab", &lab_dop_ab);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*lab_dop_at", &lab_dop_at);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*lab_dop_eb", &lab_dop_eb);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*lab_dop_th", &lab_dop_th);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*lab_unit_zb", &lab_unit_zb);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*lab_unit_zt", &lab_unit_zt);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*lab_unit_ab", &lab_unit_ab);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*lab_unit_at", &lab_unit_at);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*lab_unit_eb", &lab_unit_eb);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*lab_unit_th", &lab_unit_th);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*run_list_box", &run_list_box);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*text_add_file", &text_add_file);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*text_daq_dir", &text_daq_dir);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*text_med_pre", &text_med_pre);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*text_local_dir", &text_local_dir);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*text_settings", &text_settings);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*text_outfile", &text_outfile);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*text_calfile", &text_calfile);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*num_last_entry", &num_last_entry);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*num_dop_zb", &num_dop_zb);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*num_dop_zt", &num_dop_zt);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*num_dop_ab", &num_dop_ab);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*num_dop_at", &num_dop_at);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*num_dop_eb", &num_dop_eb);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*num_dop_th", &num_dop_th);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*check_source", &check_source);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*check_spede", &check_spede);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*check_crex", &check_crex);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*check_cdpad", &check_cdpad);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*check_ionch", &check_ionch);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*check_singles", &check_singles);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*check_gamgam", &check_gamgam);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*check_addback", &check_addback);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*check_verbose", &check_verbose);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*but_rsync", &but_rsync);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*but_medroot", &but_medroot);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*but_build", &but_build);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*but_ana", &but_ana);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*but_mnt", &but_mnt);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*but_add", &but_add);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*but_del", &but_del);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "filelist", (void*)&filelist);
      R__insp.InspectMember("vector<string>", (void*)&filelist, "filelist.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "filestatus", (void*)&filestatus);
      R__insp.InspectMember("vector<bool>", (void*)&filestatus, "filestatus.", false);
}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_MBSorter(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::MBSorter : new ::MBSorter;
   }
   static void *newArray_MBSorter(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::MBSorter[nElements] : new ::MBSorter[nElements];
   }
   // Wrapper around operator delete
   static void delete_MBSorter(void *p) {
      delete ((::MBSorter*)p);
   }
   static void deleteArray_MBSorter(void *p) {
      delete [] ((::MBSorter*)p);
   }
   static void destruct_MBSorter(void *p) {
      typedef ::MBSorter current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::MBSorter

namespace ROOTDict {
   void vectorlEboolgR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlEboolgR_Dictionary();
   static void *new_vectorlEboolgR(void *p = 0);
   static void *newArray_vectorlEboolgR(Long_t size, void *p);
   static void delete_vectorlEboolgR(void *p);
   static void deleteArray_vectorlEboolgR(void *p);
   static void destruct_vectorlEboolgR(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const vector<bool>*)
   {
      vector<bool> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<bool>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<bool>", -2, "vectorbool.dll", 0,
                  typeid(vector<bool>), ::ROOT::DefineBehavior(ptr, ptr),
                  0, &vectorlEboolgR_Dictionary, isa_proxy, 0,
                  sizeof(vector<bool>) );
      instance.SetNew(&new_vectorlEboolgR);
      instance.SetNewArray(&newArray_vectorlEboolgR);
      instance.SetDelete(&delete_vectorlEboolgR);
      instance.SetDeleteArray(&deleteArray_vectorlEboolgR);
      instance.SetDestructor(&destruct_vectorlEboolgR);
      instance.AdoptCollectionProxyInfo( ::ROOT::TCollectionProxyInfo::Generate( ::ROOT::TCollectionProxyInfo::Pushback< vector<bool> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<bool>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEboolgR_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const vector<bool>*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_vectorlEboolgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<bool> : new vector<bool>;
   }
   static void *newArray_vectorlEboolgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<bool>[nElements] : new vector<bool>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEboolgR(void *p) {
      delete ((vector<bool>*)p);
   }
   static void deleteArray_vectorlEboolgR(void *p) {
      delete [] ((vector<bool>*)p);
   }
   static void destruct_vectorlEboolgR(void *p) {
      typedef vector<bool> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class vector<bool>

namespace ROOTDict {
   void vectorlEstringgR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlEstringgR_Dictionary();
   static void *new_vectorlEstringgR(void *p = 0);
   static void *newArray_vectorlEstringgR(Long_t size, void *p);
   static void delete_vectorlEstringgR(void *p);
   static void deleteArray_vectorlEstringgR(void *p);
   static void destruct_vectorlEstringgR(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const vector<string>*)
   {
      vector<string> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<string>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<string>", -2, "prec_stl/vector", 49,
                  typeid(vector<string>), ::ROOT::DefineBehavior(ptr, ptr),
                  0, &vectorlEstringgR_Dictionary, isa_proxy, 0,
                  sizeof(vector<string>) );
      instance.SetNew(&new_vectorlEstringgR);
      instance.SetNewArray(&newArray_vectorlEstringgR);
      instance.SetDelete(&delete_vectorlEstringgR);
      instance.SetDeleteArray(&deleteArray_vectorlEstringgR);
      instance.SetDestructor(&destruct_vectorlEstringgR);
      instance.AdoptCollectionProxyInfo( ::ROOT::TCollectionProxyInfo::Generate( ::ROOT::TCollectionProxyInfo::Pushback< vector<string> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<string>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEstringgR_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const vector<string>*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_vectorlEstringgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<string> : new vector<string>;
   }
   static void *newArray_vectorlEstringgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<string>[nElements] : new vector<string>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEstringgR(void *p) {
      delete ((vector<string>*)p);
   }
   static void deleteArray_vectorlEstringgR(void *p) {
      delete [] ((vector<string>*)p);
   }
   static void destruct_vectorlEstringgR(void *p) {
      typedef vector<string> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class vector<string>

/********************************************************
* mb_sorter_dict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtablemb_sorter_dict();

extern "C" void G__set_cpp_environmentmb_sorter_dict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("MBSorter.hh");
  G__cpp_reset_tagtablemb_sorter_dict();
}
#include <new>
extern "C" int G__cpp_dllrevmb_sorter_dict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* MBSorter */
static int G__mb_sorter_dict_364_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const MBSorter*) G__getstructoffset())->GetListOfSignals());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mb_sorter_dict_364_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((MBSorter*) G__getstructoffset())->Connect((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1])
, (void*) G__int(libp->para[2]), (const char*) G__int(libp->para[3])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mb_sorter_dict_364_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 3:
      G__letint(result7, 103, (long) ((MBSorter*) G__getstructoffset())->Disconnect((const char*) G__int(libp->para[0]), (void*) G__int(libp->para[1])
, (const char*) G__int(libp->para[2])));
      break;
   case 2:
      G__letint(result7, 103, (long) ((MBSorter*) G__getstructoffset())->Disconnect((const char*) G__int(libp->para[0]), (void*) G__int(libp->para[1])));
      break;
   case 1:
      G__letint(result7, 103, (long) ((MBSorter*) G__getstructoffset())->Disconnect((const char*) G__int(libp->para[0])));
      break;
   case 0:
      G__letint(result7, 103, (long) ((MBSorter*) G__getstructoffset())->Disconnect());
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mb_sorter_dict_364_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      ((MBSorter*) G__getstructoffset())->HighPriority((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1]));
      G__setnull(result7);
      break;
   case 1:
      ((MBSorter*) G__getstructoffset())->HighPriority((const char*) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mb_sorter_dict_364_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      ((MBSorter*) G__getstructoffset())->LowPriority((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1]));
      G__setnull(result7);
      break;
   case 1:
      ((MBSorter*) G__getstructoffset())->LowPriority((const char*) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mb_sorter_dict_364_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   const int imax = 6, dmax = 8, umax = 50;
   int objsize, type, i, icnt = 0, dcnt = 0, ucnt = 0;
   G__value *pval;
   G__int64 lval[imax] = {0};
   double dval[dmax] = {0};
   union { G__int64 lval; double dval; } u[umax] = {{0}};
   lval[icnt] = G__getstructoffset(); icnt++; // this pointer
   for (i = 0; i < libp->paran; i++) {
      type = G__value_get_type(&libp->para[i]);
      pval = &libp->para[i];
      if (isupper(type))
         objsize = G__LONGALLOC;
      else
         objsize = G__sizeof(pval);
      switch (type) {
         case 'c': case 'b': case 's': case 'r': objsize = sizeof(int); break;
         case 'f': objsize = sizeof(double); break;
      }
#ifdef G__VAARG_PASS_BY_REFERENCE
      if (objsize > G__VAARG_PASS_BY_REFERENCE) {
         if (pval->ref > 0x1000) {
            if (icnt < imax) {
               lval[icnt] = pval->ref; icnt++;
            } else {
               u[ucnt].lval = pval->ref; ucnt++;
            }
         } else {
            if (icnt < imax) {
               lval[icnt] = G__int(*pval); icnt++;
            } else {
               u[ucnt].lval = G__int(*pval); ucnt++;
            }
         }
         type = 'z';
      }
#endif
      switch (type) {
         case 'n': case 'm':
            if (icnt < imax) {
               lval[icnt] = (G__int64)G__Longlong(*pval); icnt++;
            } else {
               u[ucnt].lval = (G__int64)G__Longlong(*pval); ucnt++;
            } break;
         case 'f': case 'd':
            if (dcnt < dmax) {
               dval[dcnt] = G__double(*pval); dcnt++;
            } else {
               u[ucnt].dval = G__double(*pval); ucnt++;
            } break;
         case 'z': break;
         case 'u':
            if (objsize >= 16) {
               memcpy(&u[ucnt].lval, (void*)pval->obj.i, objsize);
               ucnt += objsize/8;
               break;
            }
            // objsize < 16 -> fall through
         case 'g': case 'c': case 'b': case 'r': case 's': case 'h': case 'i':
         case 'k': case 'l':
         default:
            if (icnt < imax) {
               lval[icnt] = G__int(*pval); icnt++;
            } else {
               u[ucnt].lval = G__int(*pval); ucnt++;
            } break;
      }
      if (ucnt >= 50) printf("EmitVA: more than 56 var args\n");
   }
      ((MBSorter*) G__getstructoffset())->EmitVA((const char*) G__int(libp->para[0]), (Int_t) G__int(libp->para[1]), dval[0], dval[1], dval[2], dval[3], dval[4], dval[5], dval[6], dval[7], lval[3], lval[4], lval[5], u[0].lval, u[1].lval, u[2].lval, u[3].lval, u[4].lval, u[5].lval, u[6].lval, u[7].lval, u[8].lval, u[9].lval, u[10].lval, u[11].lval, u[12].lval, u[13].lval, u[14].lval, u[15].lval, u[16].lval, u[17].lval, u[18].lval, u[19].lval, u[20].lval, u[21].lval, u[22].lval, u[23].lval, u[24].lval, u[25].lval, u[26].lval, u[27].lval, u[28].lval, u[29].lval, u[30].lval, u[31].lval, u[32].lval, u[33].lval, u[34].lval, u[35].lval, u[36].lval, u[37].lval, u[38].lval, u[39].lval, u[40].lval, u[41].lval, u[42].lval, u[43].lval, u[44].lval, u[45].lval, u[46].lval, u[47].lval, u[48].lval, u[49].lval);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mb_sorter_dict_364_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MBSorter*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mb_sorter_dict_364_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MBSorter*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mb_sorter_dict_364_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MBSorter*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Long_t*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mb_sorter_dict_364_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MBSorter*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Double_t) G__double(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mb_sorter_dict_364_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MBSorter*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Long_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mb_sorter_dict_364_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MBSorter*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Long64_t) G__Longlong(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mb_sorter_dict_364_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MBSorter*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (ULong64_t) G__ULonglong(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mb_sorter_dict_364_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MBSorter*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Bool_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mb_sorter_dict_364_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MBSorter*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Char_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mb_sorter_dict_364_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MBSorter*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (UChar_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mb_sorter_dict_364_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MBSorter*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Short_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mb_sorter_dict_364_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MBSorter*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (UShort_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mb_sorter_dict_364_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MBSorter*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Int_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mb_sorter_dict_364_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MBSorter*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mb_sorter_dict_364_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MBSorter*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (ULong_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mb_sorter_dict_364_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MBSorter*) G__getstructoffset())->Emit((const char*) G__int(libp->para[0]), (Float_t) G__double(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mb_sorter_dict_364_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MBSorter*) G__getstructoffset())->Destroyed();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mb_sorter_dict_364_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MBSorter*) G__getstructoffset())->ChangedBy((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mb_sorter_dict_364_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MBSorter*) G__getstructoffset())->Message((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mb_sorter_dict_364_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   MBSorter* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new MBSorter[n];
     } else {
       p = new((void*) gvp) MBSorter[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new MBSorter;
     } else {
       p = new((void*) gvp) MBSorter;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__mb_sorter_dictLN_MBSorter));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mb_sorter_dict_364_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MBSorter*) G__getstructoffset())->on_add_clicked();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mb_sorter_dict_364_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MBSorter*) G__getstructoffset())->on_del_clicked();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mb_sorter_dict_364_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MBSorter*) G__getstructoffset())->on_rsync_clicked();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mb_sorter_dict_364_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MBSorter*) G__getstructoffset())->on_medroot_clicked();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mb_sorter_dict_364_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MBSorter*) G__getstructoffset())->on_build_clicked();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mb_sorter_dict_364_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MBSorter*) G__getstructoffset())->on_ana_clicked();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mb_sorter_dict_364_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MBSorter*) G__getstructoffset())->on_mnt_clicked();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mb_sorter_dict_364_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) MBSorter::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mb_sorter_dict_364_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) MBSorter::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mb_sorter_dict_364_0_36(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) MBSorter::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mb_sorter_dict_364_0_37(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      MBSorter::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mb_sorter_dict_364_0_38(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const MBSorter*) G__getstructoffset())->IsA());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mb_sorter_dict_364_0_39(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MBSorter*) G__getstructoffset())->ShowMembers(*(TMemberInspector*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mb_sorter_dict_364_0_40(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MBSorter*) G__getstructoffset())->Streamer(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mb_sorter_dict_364_0_41(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MBSorter*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mb_sorter_dict_364_0_42(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) MBSorter::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mb_sorter_dict_364_0_43(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) MBSorter::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mb_sorter_dict_364_0_44(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) MBSorter::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__mb_sorter_dict_364_0_45(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) MBSorter::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef MBSorter G__TMBSorter;
static int G__mb_sorter_dict_364_0_46(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (MBSorter*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((MBSorter*) (soff+(sizeof(MBSorter)*i)))->~G__TMBSorter();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (MBSorter*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((MBSorter*) (soff))->~G__TMBSorter();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* MBSorter */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncmb_sorter_dict {
 public:
  G__Sizep2memfuncmb_sorter_dict(): p(&G__Sizep2memfuncmb_sorter_dict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncmb_sorter_dict::*p)();
};

size_t G__get_sizep2memfuncmb_sorter_dict()
{
  G__Sizep2memfuncmb_sorter_dict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancemb_sorter_dict() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetablemb_sorter_dict() {

   /* Setting up typedef entry */
   G__search_typename2("Char_t",99,-1,0,-1);
   G__setnewtype(-1,"Signed Character 1 byte (char)",0);
   G__search_typename2("UChar_t",98,-1,0,-1);
   G__setnewtype(-1,"Unsigned Character 1 byte (unsigned char)",0);
   G__search_typename2("Short_t",115,-1,0,-1);
   G__setnewtype(-1,"Signed Short integer 2 bytes (short)",0);
   G__search_typename2("UShort_t",114,-1,0,-1);
   G__setnewtype(-1,"Unsigned Short integer 2 bytes (unsigned short)",0);
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("UInt_t",104,-1,0,-1);
   G__setnewtype(-1,"Unsigned integer 4 bytes (unsigned int)",0);
   G__search_typename2("Long_t",108,-1,0,-1);
   G__setnewtype(-1,"Signed long integer 8 bytes (long)",0);
   G__search_typename2("ULong_t",107,-1,0,-1);
   G__setnewtype(-1,"Unsigned long integer 8 bytes (unsigned long)",0);
   G__search_typename2("Float_t",102,-1,0,-1);
   G__setnewtype(-1,"Float 4 bytes (float)",0);
   G__search_typename2("Double_t",100,-1,0,-1);
   G__setnewtype(-1,"Double 8 bytes",0);
   G__search_typename2("Bool_t",103,-1,0,-1);
   G__setnewtype(-1,"Boolean (0=false, 1=true) (bool)",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("Long64_t",110,-1,0,-1);
   G__setnewtype(-1,"Portable signed long integer 8 bytes",0);
   G__search_typename2("ULong64_t",109,-1,0,-1);
   G__setnewtype(-1,"Portable unsigned long integer 8 bytes",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__mb_sorter_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__mb_sorter_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__mb_sorter_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__mb_sorter_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__mb_sorter_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__mb_sorter_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__mb_sorter_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__mb_sorter_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__mb_sorter_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__mb_sorter_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<UInt_t,Int_t>",117,G__get_linked_tagnum(&G__mb_sorter_dictLN_pairlEunsignedsPintcOintgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__mb_sorter_dictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__mb_sorter_dictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__mb_sorter_dictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__mb_sorter_dictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__mb_sorter_dictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__mb_sorter_dictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<unsigned int,int> >",117,G__get_linked_tagnum(&G__mb_sorter_dictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__mb_sorter_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__mb_sorter_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__mb_sorter_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__mb_sorter_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__mb_sorter_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<string>",117,G__get_linked_tagnum(&G__mb_sorter_dictLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__mb_sorter_dictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__mb_sorter_dictLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__mb_sorter_dictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__mb_sorter_dictLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* MBSorter */
static void G__setup_memvarMBSorter(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__mb_sorter_dictLN_MBSorter));
   { MBSorter *p; p=(MBSorter*)0x1000; if (p) { }
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TQObjSender),-1,-1,4,"fQObject=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGMainFrame),-1,-1,2,"main_frame=",0,"main frame");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGVerticalFrame),-1,-1,2,"left_frame=",0,"left frame for run list");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGVerticalFrame),-1,-1,2,"centre_frame=",0,"right frame for input files and directories, etc");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGHorizontalFrame),-1,-1,2,"right_frame=",0,"right frame for experimental definitions and Doppler");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGCompositeFrame),-1,-1,2,"comp_frame_0=",0,"composite frame for rsync");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGCompositeFrame),-1,-1,2,"comp_frame_1=",0,"composite frame for MedToRoot");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGCompositeFrame),-1,-1,2,"comp_frame_2=",0,"composite frame for TreeBuilder");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGCompositeFrame),-1,-1,2,"comp_frame_3=",0,"composite frame for TreeAna");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGVerticalFrame),-1,-1,2,"dop_frame_0=",0,"vertical frame for Doppler labels");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGVerticalFrame),-1,-1,2,"dop_frame_1=",0,"vertical frame for Doppler values");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGVerticalFrame),-1,-1,2,"dop_frame_2=",0,"vertical frame for Doppler units");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGVerticalFrame),-1,-1,2,"sub_frame_0=",0,"sub frame for directory boxes");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGHorizontalFrame),-1,-1,2,"sub_frame_1=",0,"sub-sub frame for daq directory");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGHorizontalFrame),-1,-1,2,"sub_frame_2=",0,"sub-sub frame for local directory");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGHorizontalFrame),-1,-1,2,"sub_frame_3=",0,"sub frame for add/remove files buttons");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGVerticalFrame),-1,-1,2,"sub_frame_4=",0,"sub frame for MedToRoot buttons/boxes");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGHorizontalFrame),-1,-1,2,"sub_frame_5=",0,"sub-sub frame for settings file");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGHorizontalFrame),-1,-1,2,"sub_frame_6=",0,"sub-sub frame for conversion options");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGVerticalFrame),-1,-1,2,"sub_frame_7=",0,"sub frame for TreeBuilder buttons/boxes");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGHorizontalFrame),-1,-1,2,"sub_frame_8=",0,"sub-sub frame for output file");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGHorizontalFrame),-1,-1,2,"sub_frame_9=",0,"sub-sub frame for calibration file");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGHorizontalFrame),-1,-1,2,"sub_frame_10=",0,"sub-sub frame for TreeBuilder check buttons");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGVerticalFrame),-1,-1,2,"sub_frame_11=",0,"sub frame for TreeAna buttons/boxes");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGHorizontalFrame),-1,-1,2,"sub_frame_12=",0,"sub-sub frame for TreeAna check buttons");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGHorizontal3DLine),-1,-1,2,"fHorizontal_0=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGHorizontal3DLine),-1,-1,2,"fHorizontal_1=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGHorizontal3DLine),-1,-1,2,"fHorizontal_2=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGHorizontal3DLine),-1,-1,2,"fHorizontal_3=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGVertical3DLine),-1,-1,2,"fVertical_0=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGVertical3DLine),-1,-1,2,"fVertical_1=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGLabel),-1,-1,2,"lab_run_files=",0,"label for run file list");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGLabel),-1,-1,2,"lab_daq_dir=",0,"label for daq directory");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGLabel),-1,-1,2,"lab_med_pre=",0,"label for med file prefix");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGLabel),-1,-1,2,"lab_local_dir=",0,"label for local directory");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGLabel),-1,-1,2,"lab_settings=",0,"label for settings file");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGLabel),-1,-1,2,"lab_last_entry=",0,"label for last entry number");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGLabel),-1,-1,2,"lab_outfile=",0,"label for output filename");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGLabel),-1,-1,2,"lab_outsuffix=",0,"display suffix of output filename");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGLabel),-1,-1,2,"lab_calfile=",0,"label for calibration file");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGLabel),-1,-1,2,"lab_dop_zb=",0,"label for Z of beam");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGLabel),-1,-1,2,"lab_dop_zt=",0,"label for Z of target");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGLabel),-1,-1,2,"lab_dop_ab=",0,"label for A of beam");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGLabel),-1,-1,2,"lab_dop_at=",0,"label for A of target");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGLabel),-1,-1,2,"lab_dop_eb=",0,"label for energy of beam");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGLabel),-1,-1,2,"lab_dop_th=",0,"label for target thickness");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGLabel),-1,-1,2,"lab_unit_zb=",0,"label for Z of beam");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGLabel),-1,-1,2,"lab_unit_zt=",0,"label for Z of target");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGLabel),-1,-1,2,"lab_unit_ab=",0,"label for A of beam");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGLabel),-1,-1,2,"lab_unit_at=",0,"label for A of target");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGLabel),-1,-1,2,"lab_unit_eb=",0,"label for energy of beam");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGLabel),-1,-1,2,"lab_unit_th=",0,"label for target thickness");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGListBox),-1,-1,2,"run_list_box=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGTextEntry),-1,-1,2,"text_add_file=",0,"text entry for adding a file");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGTextEntry),-1,-1,2,"text_daq_dir=",0,"text entry for daq directory");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGTextEntry),-1,-1,2,"text_med_pre=",0,"text entry for medfile prefix");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGTextEntry),-1,-1,2,"text_local_dir=",0,"text entry for local directory");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGTextEntry),-1,-1,2,"text_settings=",0,"text entry for settings file");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGTextEntry),-1,-1,2,"text_outfile=",0,"text entry for output filename base");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGTextEntry),-1,-1,2,"text_calfile=",0,"text entry for calibration file");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGNumberEntry),-1,-1,2,"num_last_entry=",0,"number for the last entry flag");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGNumberEntry),-1,-1,2,"num_dop_zb=",0,"number for the Z of beam");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGNumberEntry),-1,-1,2,"num_dop_zt=",0,"number for the Z of target");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGNumberEntry),-1,-1,2,"num_dop_ab=",0,"number for the A of beam");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGNumberEntry),-1,-1,2,"num_dop_at=",0,"number for the A of target");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGNumberEntry),-1,-1,2,"num_dop_eb=",0,"number for the beam energy");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGNumberEntry),-1,-1,2,"num_dop_th=",0,"number for the target thickness");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGCheckButton),-1,-1,2,"check_source=",0,"check button for source selection");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGCheckButton),-1,-1,2,"check_spede=",0,"check button for spede selection");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGCheckButton),-1,-1,2,"check_crex=",0,"check button for crex selection");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGCheckButton),-1,-1,2,"check_cdpad=",0,"check button for CD+Pad for electrons");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGCheckButton),-1,-1,2,"check_ionch=",0,"check button for ionisation chamber");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGCheckButton),-1,-1,2,"check_singles=",0,"check button for singles tree");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGCheckButton),-1,-1,2,"check_gamgam=",0,"check button for gamma-gamma events in tree");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGCheckButton),-1,-1,2,"check_addback=",0,"check button for addback on/off");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGCheckButton),-1,-1,2,"check_verbose=",0,"check button for verbose output");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGTextButton),-1,-1,2,"but_rsync=",0,"button to do rsync");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGTextButton),-1,-1,2,"but_medroot=",0,"button to do MedToRoot");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGTextButton),-1,-1,2,"but_build=",0,"button to do TreeBuilder");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGTextButton),-1,-1,2,"but_ana=",0,"button to do TreeAna");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGTextButton),-1,-1,2,"but_mnt=",0,"button to do MntAna");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGTextButton),-1,-1,2,"but_add=",0,"button to add files");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TGTextButton),-1,-1,2,"but_del=",0,"button to remove files");
   G__memvar_setup((void*)0,108,0,0,-1,-1,-1,4,"G__virtualinfo=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->filelist)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_vectorlEstringcOallocatorlEstringgRsPgR),G__defined_typename("vector<string>"),-1,1,"filelist=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->filestatus)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_vectorlEboolcOallocatorlEboolgRsPgR),G__defined_typename("vector<bool>"),-1,1,"filestatus=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__mb_sorter_dictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarmb_sorter_dict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncMBSorter(void) {
   /* MBSorter */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__mb_sorter_dictLN_MBSorter));
   G__memfunc_setup("GetListOfSignals",1602,G__mb_sorter_dict_364_0_1, 85, G__get_linked_tagnum(&G__mb_sorter_dictLN_TList), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Connect",714,G__mb_sorter_dict_364_0_2, 103, -1, G__defined_typename("Bool_t"), 0, 4, 1, 1, 0, 
"C - - 10 - sig C - - 10 - cl "
"Y - - 0 - rcvr C - - 10 - slt", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Disconnect",1034,G__mb_sorter_dict_364_0_3, 103, -1, G__defined_typename("Bool_t"), 0, 3, 1, 1, 0, 
"C - - 10 '0' sig Y - - 0 '0' rcvr "
"C - - 10 '0' slt", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("HighPriority",1250,G__mb_sorter_dict_364_0_4, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal_name C - - 10 '0' slot_name", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("LowPriority",1172,G__mb_sorter_dict_364_0_5, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal_name C - - 10 '0' slot_name", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("EmitVA",550,G__mb_sorter_dict_364_0_6, 121, -1, -1, 0, 2, 8, 1, 0, 
"C - - 10 - signal i - 'Int_t' 0 - nargs", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__mb_sorter_dict_364_0_7, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - signal", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__mb_sorter_dict_364_0_8, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal C - - 10 - params", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__mb_sorter_dict_364_0_9, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal L - 'Long_t' 0 - paramArr", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__mb_sorter_dict_364_0_10, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal d - 'Double_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__mb_sorter_dict_364_0_11, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal l - 'Long_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__mb_sorter_dict_364_0_12, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal n - 'Long64_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__mb_sorter_dict_364_0_13, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal m - 'ULong64_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__mb_sorter_dict_364_0_14, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal g - 'Bool_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__mb_sorter_dict_364_0_15, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal c - 'Char_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__mb_sorter_dict_364_0_16, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal b - 'UChar_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__mb_sorter_dict_364_0_17, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal s - 'Short_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__mb_sorter_dict_364_0_18, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal r - 'UShort_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__mb_sorter_dict_364_0_19, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal i - 'Int_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__mb_sorter_dict_364_0_20, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal h - 'UInt_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__mb_sorter_dict_364_0_21, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal k - 'ULong_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Emit",399,G__mb_sorter_dict_364_0_22, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - signal f - 'Float_t' 0 - param", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Destroyed",947,G__mb_sorter_dict_364_0_23, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ChangedBy",869,G__mb_sorter_dict_364_0_24, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - method", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Message",709,G__mb_sorter_dict_364_0_25, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - msg", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MBSorter",782,G__mb_sorter_dict_364_0_26, 105, G__get_linked_tagnum(&G__mb_sorter_dictLN_MBSorter), -1, 0, 0, 1, 1, 0, "", "constructor", (void*) NULL, 0);
   G__memfunc_setup("on_add_clicked",1427,G__mb_sorter_dict_364_0_27, 121, -1, -1, 0, 0, 1, 1, 0, "", "add file function", (void*) NULL, 0);
   G__memfunc_setup("on_del_clicked",1439,G__mb_sorter_dict_364_0_28, 121, -1, -1, 0, 0, 1, 1, 0, "", "remove file function", (void*) NULL, 0);
   G__memfunc_setup("on_rsync_clicked",1689,G__mb_sorter_dict_364_0_29, 121, -1, -1, 0, 0, 1, 1, 0, "", "rsync function", (void*) NULL, 0);
   G__memfunc_setup("on_medroot_clicked",1892,G__mb_sorter_dict_364_0_30, 121, -1, -1, 0, 0, 1, 1, 0, "", "MedToRoot function", (void*) NULL, 0);
   G__memfunc_setup("on_build_clicked",1658,G__mb_sorter_dict_364_0_31, 121, -1, -1, 0, 0, 1, 1, 0, "", "TreeBuilder function", (void*) NULL, 0);
   G__memfunc_setup("on_ana_clicked",1434,G__mb_sorter_dict_364_0_32, 121, -1, -1, 0, 0, 1, 1, 0, "", "TreeAna function", (void*) NULL, 0);
   G__memfunc_setup("on_mnt_clicked",1465,G__mb_sorter_dict_364_0_33, 121, -1, -1, 0, 0, 1, 1, 0, "", "MntAna function", (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__mb_sorter_dict_364_0_34, 85, G__get_linked_tagnum(&G__mb_sorter_dictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&MBSorter::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__mb_sorter_dict_364_0_35, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&MBSorter::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__mb_sorter_dict_364_0_36, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&MBSorter::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__mb_sorter_dict_364_0_37, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&MBSorter::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,G__mb_sorter_dict_364_0_38, 85, G__get_linked_tagnum(&G__mb_sorter_dictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,G__mb_sorter_dict_364_0_39, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,G__mb_sorter_dict_364_0_40, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__mb_sorter_dict_364_0_41, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__mb_sorter_dict_364_0_42, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&MBSorter::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__mb_sorter_dict_364_0_43, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&MBSorter::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__mb_sorter_dict_364_0_44, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&MBSorter::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__mb_sorter_dict_364_0_45, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&MBSorter::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~MBSorter", 908, G__mb_sorter_dict_364_0_46, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncmb_sorter_dict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {
}

static void G__cpp_setup_global6() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalmb_sorter_dict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
  G__cpp_setup_global6();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcmb_sorter_dict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__mb_sorter_dictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__mb_sorter_dictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__mb_sorter_dictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__mb_sorter_dictLN_vectorlEboolcOallocatorlEboolgRsPgR = { "vector<bool,allocator<bool> >" , 99 , -1 };
G__linked_taginfo G__mb_sorter_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__mb_sorter_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__mb_sorter_dictLN_TList = { "TList" , 99 , -1 };
G__linked_taginfo G__mb_sorter_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__mb_sorter_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__mb_sorter_dictLN_TQObjSender = { "TQObjSender" , 99 , -1 };
G__linked_taginfo G__mb_sorter_dictLN_pairlEunsignedsPintcOintgR = { "pair<unsigned int,int>" , 115 , -1 };
G__linked_taginfo G__mb_sorter_dictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR = { "vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >" , 99 , -1 };
G__linked_taginfo G__mb_sorter_dictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >::iterator>" , 99 , -1 };
G__linked_taginfo G__mb_sorter_dictLN_TGCompositeFrame = { "TGCompositeFrame" , 99 , -1 };
G__linked_taginfo G__mb_sorter_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__mb_sorter_dictLN_TGTextButton = { "TGTextButton" , 99 , -1 };
G__linked_taginfo G__mb_sorter_dictLN_TGVerticalFrame = { "TGVerticalFrame" , 99 , -1 };
G__linked_taginfo G__mb_sorter_dictLN_TGHorizontalFrame = { "TGHorizontalFrame" , 99 , -1 };
G__linked_taginfo G__mb_sorter_dictLN_TGMainFrame = { "TGMainFrame" , 99 , -1 };
G__linked_taginfo G__mb_sorter_dictLN_TGTextEntry = { "TGTextEntry" , 99 , -1 };
G__linked_taginfo G__mb_sorter_dictLN_TGCheckButton = { "TGCheckButton" , 99 , -1 };
G__linked_taginfo G__mb_sorter_dictLN_TGNumberEntry = { "TGNumberEntry" , 99 , -1 };
G__linked_taginfo G__mb_sorter_dictLN_TGLabel = { "TGLabel" , 99 , -1 };
G__linked_taginfo G__mb_sorter_dictLN_TGListBox = { "TGListBox" , 99 , -1 };
G__linked_taginfo G__mb_sorter_dictLN_TGHorizontal3DLine = { "TGHorizontal3DLine" , 99 , -1 };
G__linked_taginfo G__mb_sorter_dictLN_TGVertical3DLine = { "TGVertical3DLine" , 99 , -1 };
G__linked_taginfo G__mb_sorter_dictLN_MBSorter = { "MBSorter" , 99 , -1 };
G__linked_taginfo G__mb_sorter_dictLN_vectorlEstringcOallocatorlEstringgRsPgR = { "vector<string,allocator<string> >" , 99 , -1 };
G__linked_taginfo G__mb_sorter_dictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<string,allocator<string> >::iterator>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtablemb_sorter_dict() {
  G__mb_sorter_dictLN_TClass.tagnum = -1 ;
  G__mb_sorter_dictLN_TBuffer.tagnum = -1 ;
  G__mb_sorter_dictLN_TMemberInspector.tagnum = -1 ;
  G__mb_sorter_dictLN_vectorlEboolcOallocatorlEboolgRsPgR.tagnum = -1 ;
  G__mb_sorter_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__mb_sorter_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__mb_sorter_dictLN_TList.tagnum = -1 ;
  G__mb_sorter_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__mb_sorter_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__mb_sorter_dictLN_TQObjSender.tagnum = -1 ;
  G__mb_sorter_dictLN_pairlEunsignedsPintcOintgR.tagnum = -1 ;
  G__mb_sorter_dictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR.tagnum = -1 ;
  G__mb_sorter_dictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__mb_sorter_dictLN_TGCompositeFrame.tagnum = -1 ;
  G__mb_sorter_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__mb_sorter_dictLN_TGTextButton.tagnum = -1 ;
  G__mb_sorter_dictLN_TGVerticalFrame.tagnum = -1 ;
  G__mb_sorter_dictLN_TGHorizontalFrame.tagnum = -1 ;
  G__mb_sorter_dictLN_TGMainFrame.tagnum = -1 ;
  G__mb_sorter_dictLN_TGTextEntry.tagnum = -1 ;
  G__mb_sorter_dictLN_TGCheckButton.tagnum = -1 ;
  G__mb_sorter_dictLN_TGNumberEntry.tagnum = -1 ;
  G__mb_sorter_dictLN_TGLabel.tagnum = -1 ;
  G__mb_sorter_dictLN_TGListBox.tagnum = -1 ;
  G__mb_sorter_dictLN_TGHorizontal3DLine.tagnum = -1 ;
  G__mb_sorter_dictLN_TGVertical3DLine.tagnum = -1 ;
  G__mb_sorter_dictLN_MBSorter.tagnum = -1 ;
  G__mb_sorter_dictLN_vectorlEstringcOallocatorlEstringgRsPgR.tagnum = -1 ;
  G__mb_sorter_dictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtablemb_sorter_dict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__mb_sorter_dictLN_TClass);
   G__get_linked_tagnum_fwd(&G__mb_sorter_dictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__mb_sorter_dictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__mb_sorter_dictLN_vectorlEboolcOallocatorlEboolgRsPgR);
   G__get_linked_tagnum_fwd(&G__mb_sorter_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__mb_sorter_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__mb_sorter_dictLN_TList);
   G__get_linked_tagnum_fwd(&G__mb_sorter_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__mb_sorter_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__mb_sorter_dictLN_TQObjSender);
   G__get_linked_tagnum_fwd(&G__mb_sorter_dictLN_pairlEunsignedsPintcOintgR);
   G__get_linked_tagnum_fwd(&G__mb_sorter_dictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__mb_sorter_dictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__mb_sorter_dictLN_TGCompositeFrame);
   G__get_linked_tagnum_fwd(&G__mb_sorter_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__mb_sorter_dictLN_TGTextButton);
   G__get_linked_tagnum_fwd(&G__mb_sorter_dictLN_TGVerticalFrame);
   G__get_linked_tagnum_fwd(&G__mb_sorter_dictLN_TGHorizontalFrame);
   G__get_linked_tagnum_fwd(&G__mb_sorter_dictLN_TGMainFrame);
   G__get_linked_tagnum_fwd(&G__mb_sorter_dictLN_TGTextEntry);
   G__get_linked_tagnum_fwd(&G__mb_sorter_dictLN_TGCheckButton);
   G__get_linked_tagnum_fwd(&G__mb_sorter_dictLN_TGNumberEntry);
   G__get_linked_tagnum_fwd(&G__mb_sorter_dictLN_TGLabel);
   G__get_linked_tagnum_fwd(&G__mb_sorter_dictLN_TGListBox);
   G__get_linked_tagnum_fwd(&G__mb_sorter_dictLN_TGHorizontal3DLine);
   G__get_linked_tagnum_fwd(&G__mb_sorter_dictLN_TGVertical3DLine);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__mb_sorter_dictLN_MBSorter),sizeof(MBSorter),-1,263424,(char*)NULL,G__setup_memvarMBSorter,G__setup_memfuncMBSorter);
   G__get_linked_tagnum_fwd(&G__mb_sorter_dictLN_vectorlEstringcOallocatorlEstringgRsPgR);
   G__get_linked_tagnum_fwd(&G__mb_sorter_dictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR);
}
extern "C" void G__cpp_setupmb_sorter_dict(void) {
  G__check_setup_version(30051515,"G__cpp_setupmb_sorter_dict()");
  G__set_cpp_environmentmb_sorter_dict();
  G__cpp_setup_tagtablemb_sorter_dict();

  G__cpp_setup_inheritancemb_sorter_dict();

  G__cpp_setup_typetablemb_sorter_dict();

  G__cpp_setup_memvarmb_sorter_dict();

  G__cpp_setup_memfuncmb_sorter_dict();
  G__cpp_setup_globalmb_sorter_dict();
  G__cpp_setup_funcmb_sorter_dict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncmb_sorter_dict();
  return;
}
class G__cpp_setup_initmb_sorter_dict {
  public:
    G__cpp_setup_initmb_sorter_dict() { G__add_setup_func("mb_sorter_dict",(G__incsetup)(&G__cpp_setupmb_sorter_dict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initmb_sorter_dict() { G__remove_setup_func("mb_sorter_dict"); }
};
G__cpp_setup_initmb_sorter_dict G__cpp_setup_initializermb_sorter_dict;

