/********************************************************************
* mb_sorter_dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error mb_sorter_dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablemb_sorter_dict();
extern void G__cpp_setup_inheritancemb_sorter_dict();
extern void G__cpp_setup_typetablemb_sorter_dict();
extern void G__cpp_setup_memvarmb_sorter_dict();
extern void G__cpp_setup_globalmb_sorter_dict();
extern void G__cpp_setup_memfuncmb_sorter_dict();
extern void G__cpp_setup_funcmb_sorter_dict();
extern void G__set_cpp_environmentmb_sorter_dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "MBSorter.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__mb_sorter_dictLN_TClass;
extern G__linked_taginfo G__mb_sorter_dictLN_TBuffer;
extern G__linked_taginfo G__mb_sorter_dictLN_TMemberInspector;
extern G__linked_taginfo G__mb_sorter_dictLN_vectorlEboolcOallocatorlEboolgRsPgR;
extern G__linked_taginfo G__mb_sorter_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__mb_sorter_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__mb_sorter_dictLN_TList;
extern G__linked_taginfo G__mb_sorter_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__mb_sorter_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__mb_sorter_dictLN_TQObjSender;
extern G__linked_taginfo G__mb_sorter_dictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__mb_sorter_dictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__mb_sorter_dictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__mb_sorter_dictLN_TGCompositeFrame;
extern G__linked_taginfo G__mb_sorter_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__mb_sorter_dictLN_TGTextButton;
extern G__linked_taginfo G__mb_sorter_dictLN_TGVerticalFrame;
extern G__linked_taginfo G__mb_sorter_dictLN_TGHorizontalFrame;
extern G__linked_taginfo G__mb_sorter_dictLN_TGMainFrame;
extern G__linked_taginfo G__mb_sorter_dictLN_TGTextEntry;
extern G__linked_taginfo G__mb_sorter_dictLN_TGCheckButton;
extern G__linked_taginfo G__mb_sorter_dictLN_TGNumberEntry;
extern G__linked_taginfo G__mb_sorter_dictLN_TGLabel;
extern G__linked_taginfo G__mb_sorter_dictLN_TGListBox;
extern G__linked_taginfo G__mb_sorter_dictLN_TGHorizontal3DLine;
extern G__linked_taginfo G__mb_sorter_dictLN_TGVertical3DLine;
extern G__linked_taginfo G__mb_sorter_dictLN_MBSorter;
extern G__linked_taginfo G__mb_sorter_dictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__mb_sorter_dictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
