/********************************************************************
* MntAnaDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error MntAnaDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableMntAnaDict();
extern void G__cpp_setup_inheritanceMntAnaDict();
extern void G__cpp_setup_typetableMntAnaDict();
extern void G__cpp_setup_memvarMntAnaDict();
extern void G__cpp_setup_globalMntAnaDict();
extern void G__cpp_setup_memfuncMntAnaDict();
extern void G__cpp_setup_funcMntAnaDict();
extern void G__set_cpp_environmentMntAnaDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "g_clx.hh"
#include "../mbevts/mbevts.hh"
#include "doppler.hh"
#include "hists.hh"
#include "MBGeometry.hh"
#include "SpedeGeometry.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__MntAnaDictLN_TClass;
extern G__linked_taginfo G__MntAnaDictLN_TBuffer;
extern G__linked_taginfo G__MntAnaDictLN_TMemberInspector;
extern G__linked_taginfo G__MntAnaDictLN_TObject;
extern G__linked_taginfo G__MntAnaDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__MntAnaDictLN_string;
extern G__linked_taginfo G__MntAnaDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__MntAnaDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__MntAnaDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__MntAnaDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__MntAnaDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__MntAnaDictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__MntAnaDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__MntAnaDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__MntAnaDictLN_TH1F;
extern G__linked_taginfo G__MntAnaDictLN_TTree;
extern G__linked_taginfo G__MntAnaDictLN_TBranch;
extern G__linked_taginfo G__MntAnaDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__MntAnaDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__MntAnaDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__MntAnaDictLN_mbevts;
extern G__linked_taginfo G__MntAnaDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__MntAnaDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__MntAnaDictLN_g_clx;
extern G__linked_taginfo G__MntAnaDictLN_TRandom3;
extern G__linked_taginfo G__MntAnaDictLN_doppler;
extern G__linked_taginfo G__MntAnaDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__MntAnaDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__MntAnaDictLN_TH2F;
extern G__linked_taginfo G__MntAnaDictLN_hists;
extern G__linked_taginfo G__MntAnaDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__MntAnaDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__MntAnaDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__MntAnaDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__MntAnaDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__MntAnaDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__MntAnaDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__MntAnaDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__MntAnaDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__MntAnaDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__MntAnaDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__MntAnaDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__MntAnaDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__MntAnaDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__MntAnaDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__MntAnaDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__MntAnaDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__MntAnaDictLN_TVector3;
extern G__linked_taginfo G__MntAnaDictLN_MBGeometry;
extern G__linked_taginfo G__MntAnaDictLN_SpedeGeometry;

/* STUB derived class for protected member access */
