/********************************************************************
* TreeAnaDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TreeAnaDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTreeAnaDict();
extern void G__cpp_setup_inheritanceTreeAnaDict();
extern void G__cpp_setup_typetableTreeAnaDict();
extern void G__cpp_setup_memvarTreeAnaDict();
extern void G__cpp_setup_globalTreeAnaDict();
extern void G__cpp_setup_memfuncTreeAnaDict();
extern void G__cpp_setup_funcTreeAnaDict();
extern void G__set_cpp_environmentTreeAnaDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "g_clx.hh"
#include "../mbevts/mbevts.hh"
#include "doppler.hh"
#include "hists.hh"
#include "MBGeometry.hh"
#include "SpedeGeometry.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TreeAnaDictLN_TClass;
extern G__linked_taginfo G__TreeAnaDictLN_TBuffer;
extern G__linked_taginfo G__TreeAnaDictLN_TMemberInspector;
extern G__linked_taginfo G__TreeAnaDictLN_TObject;
extern G__linked_taginfo G__TreeAnaDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__TreeAnaDictLN_string;
extern G__linked_taginfo G__TreeAnaDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TreeAnaDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TreeAnaDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TreeAnaDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TreeAnaDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TreeAnaDictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__TreeAnaDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__TreeAnaDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TreeAnaDictLN_TH1F;
extern G__linked_taginfo G__TreeAnaDictLN_TTree;
extern G__linked_taginfo G__TreeAnaDictLN_TBranch;
extern G__linked_taginfo G__TreeAnaDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__TreeAnaDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TreeAnaDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TreeAnaDictLN_mbevts;
extern G__linked_taginfo G__TreeAnaDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__TreeAnaDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TreeAnaDictLN_g_clx;
extern G__linked_taginfo G__TreeAnaDictLN_TRandom3;
extern G__linked_taginfo G__TreeAnaDictLN_doppler;
extern G__linked_taginfo G__TreeAnaDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TreeAnaDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TreeAnaDictLN_TH2F;
extern G__linked_taginfo G__TreeAnaDictLN_hists;
extern G__linked_taginfo G__TreeAnaDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TreeAnaDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TreeAnaDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TreeAnaDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TreeAnaDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TreeAnaDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TreeAnaDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TreeAnaDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TreeAnaDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TreeAnaDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TreeAnaDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TreeAnaDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TreeAnaDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TreeAnaDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TreeAnaDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TreeAnaDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TreeAnaDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TreeAnaDictLN_TVector3;
extern G__linked_taginfo G__TreeAnaDictLN_MBGeometry;
extern G__linked_taginfo G__TreeAnaDictLN_SpedeGeometry;

/* STUB derived class for protected member access */
